### ISSUE TITLE
Does Windows has the Miracast uibc API？

### ISSUE THREAD

**Issue by SongZhaozhan** [shadow578/ImmersiveMiracast#4]

**Comment by SongZhaozhan** [comment]
Dear sir, I have already read the ImmersiveMiracast's code, and found that you use the windows miracast api for cast. However, in the  Windows.Media.Miracast Namespace I didn‘t found a class which is used for UIBC such as Mouse operation . So do you have the plan to Implement this feature in the future?

**Comment by shadow578** [comment]
I'm not really sure what UIBC is, but this project is no longer maintained by me as I don't have much use for it anymore.
But you may fork the project if you'd like
